# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_nr', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('registered', models.DateField()),
                ('comments', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ghost_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_nr', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('ems', models.CharField(max_length=20)),
                ('microchip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gost', models.BooleanField()),
                ('_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.cat')),
                ('_Ghost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.ghost_cat')),
            ],
        ),
        migrations.AddField(
            model_name='ghost_cat',
            name='dam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghost_dam', to='catdb.parents'),
        ),
        migrations.AddField(
            model_name='ghost_cat',
            name='sire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghost_sire', to='catdb.parents'),
        ),
        migrations.AddField(
            model_name='cat',
            name='dam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dam', to='catdb.parents'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='catdb.parents'),
        ),
    ]
