# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catdb', '0002_auto_20160714_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 7, 14, 20, 25, 42, 324809, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
