# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catdb', '0003_cat_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dam', to='catdb.parents'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='catdb.parents'),
        ),
    ]
