# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catdb', '0004_auto_20160714_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_EMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=3)),
                ('ems', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ghost_EMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.EMS')),
            ],
        ),
        migrations.CreateModel(
            name='imp_cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_country', models.CharField(max_length=3, null=True)),
                ('org_organization', models.CharField(max_length=10, null=True)),
                ('org_reg_nr', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='microchip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('microchip_nr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='neutered',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='is_gost',
            new_name='is_ghost',
        ),
        migrations.RemoveField(
            model_name='ghost_cat',
            name='ems',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='_Cat',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='_Ghost',
        ),
        migrations.AddField(
            model_name='parents',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='catdb.cat'),
        ),
        migrations.AddField(
            model_name='parents',
            name='ghost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghost_id', to='catdb.ghost_cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='comments',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='cat',
            name='reg_nr',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='neutered',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.cat'),
        ),
        migrations.AddField(
            model_name='microchip',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.cat'),
        ),
        migrations.AddField(
            model_name='imp_cat',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.cat'),
        ),
        migrations.AddField(
            model_name='ghost_ems',
            name='ghost_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.ghost_cat'),
        ),
        migrations.AddField(
            model_name='cat_ems',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.cat'),
        ),
        migrations.AddField(
            model_name='cat_ems',
            name='ems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catdb.EMS'),
        ),
    ]
